# Generated by Django 4.2.7 on 2023-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.CharField(max_length=105),
        ),
    ]
